sudo: false
language: python
services:
  - mysql
  - redis-server
python:
  - "2.7"
env:
  matrix:
    - DB=mysql
before_script:
  - mysql -e 'create database s52585__interface;'
script:
  - ./manage.py migrate
  - ./setup.py flake8
  - ./setup.py nosetests