sudo: false
language: python
services:
  - mysql
  - redis-server
python:
  - "3.4"
env:
  matrix:
    - DB=mysql
before_script:
  - mysql -e 'create database cbng_bot;'
  - mysql -e 'source fixtures/cb_sample_data.sql' cbng_bot
script:
  - ./setup.py flake8
  - ./manage.py migrate
  - ./setup.py nosetests
