# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('classification', models.IntegerField(choices=[(0, b'Vandalism'), (1, b'Constructive'), (2, b'Skipped')])),
            ],
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=256)),
                ('article', models.CharField(max_length=256)),
                ('old_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
                ('required', models.IntegerField(default=2)),
                ('report', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, b'Not Done'), (1, b'Partially Done'), (2, b'Done')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EditGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='edit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbng_review.EditGroup'),
        ),
        migrations.AddField(
            model_name='classification',
            name='edit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbng_review.Edit'),
        ),
        migrations.AddField(
            model_name='classification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('user', 'edit')]),
        ),
    ]
