# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('article', models.CharField(max_length=256)),
                ('diff', models.CharField(max_length=512)),
                ('user', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'beaten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('node', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'cluster_node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('admin', models.IntegerField()),
                ('superadmin', models.IntegerField()),
                ('next_on_review', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vandalism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=256)),
                ('article', models.CharField(max_length=256)),
                ('heuristic', models.CharField(max_length=64)),
                ('regex', models.CharField(blank=True, max_length=2048, null=True)),
                ('reason', models.CharField(max_length=512)),
                ('old_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
                ('reverted', models.IntegerField()),
            ],
            options={
                'db_table': 'vandalism',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True)),
                ('vandalism', models.OneToOneField(db_column='revertid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cbng_report.Vandalism')),
                ('timestamp', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('vandalism', models.OneToOneField(db_column='revertid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cbng_report.Vandalism')),
                ('timestamp', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Reported'), (1, 'Invalid'), (2, 'Defer to Review Interface'), (3, 'Bug'), (4, 'Resolved')], default=0)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
    ]
